def Forca(erros=0):
    if erros == 0:
        print('__________')
        print('|        | ')
        print('|          ')
        print('|            ')
        print('|           ')
        print('| ')
        print('| ')
    elif erros == 1:
        print('__________')
        print('|        | ')
        print('|        O ')
        print('|            ')
        print('|           ')
        print('| ')
        print('| ')
    elif erros == 2:
        print('__________')
        print('|        | ')
        print('|        O ')
        print('|        |    ')
        print('|           ')
        print('| ')
        print('| ')
    elif erros == 3:
        print('__________')
        print('|        | ')
        print('|        O ')
        print('|       -|   ')
        print('|           ')
        print('| ')
        print('| ')
    elif erros == 4:
        print('__________')
        print('|        | ')
        print('|        O ')
        print('|       -|-   ')
        print('|           ')
        print('| ')
        print('| ')
    elif erros == 5:
        print('__________')
        print('|        | ')
        print('|        O ')
        print('|       -|-   ')
        print('|       /   ')
        print('| ')
        print('| ')
    elif erros == 6:
        print('__________')
        print('|        | ')
        print('|        O ')
        print('|       -|-   ')
        print('|       / \  ')
        print('| ')
        print('| Você perdeu')


        # print('__________')
        # print('|        | ')
        # print('|        O ')
        # print('|      - | - ')
        # print('|       / \ ')
        # print('| ')
        # print('| Lamento! Perdeu!')
        # print('| ')